# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneof_test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneof_test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10oneof_test.proto\"A\n\x04Test\x12\x16\n\x01\x61\x18\x01 \x01(\x0b\x32\t.MessageAH\x00\x12\x16\n\x01\x62\x18\x02 \x01(\x0b\x32\t.MessageBH\x00\x42\t\n\x07message\"\x1b\n\x08MessageA\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1b\n\x08MessageB\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x05\x62\x06proto3'
)




_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='Test.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='Test.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='Test.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=20,
  serialized_end=85,
)


_MESSAGEA = _descriptor.Descriptor(
  name='MessageA',
  full_name='MessageA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='MessageA.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=114,
)


_MESSAGEB = _descriptor.Descriptor(
  name='MessageB',
  full_name='MessageB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='MessageB.content', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=143,
)

_TEST.fields_by_name['a'].message_type = _MESSAGEA
_TEST.fields_by_name['b'].message_type = _MESSAGEB
_TEST.oneofs_by_name['message'].fields.append(
  _TEST.fields_by_name['a'])
_TEST.fields_by_name['a'].containing_oneof = _TEST.oneofs_by_name['message']
_TEST.oneofs_by_name['message'].fields.append(
  _TEST.fields_by_name['b'])
_TEST.fields_by_name['b'].containing_oneof = _TEST.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['MessageA'] = _MESSAGEA
DESCRIPTOR.message_types_by_name['MessageB'] = _MESSAGEB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'oneof_test_pb2'
  # @@protoc_insertion_point(class_scope:Test)
  })
_sym_db.RegisterMessage(Test)

MessageA = _reflection.GeneratedProtocolMessageType('MessageA', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEA,
  '__module__' : 'oneof_test_pb2'
  # @@protoc_insertion_point(class_scope:MessageA)
  })
_sym_db.RegisterMessage(MessageA)

MessageB = _reflection.GeneratedProtocolMessageType('MessageB', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEB,
  '__module__' : 'oneof_test_pb2'
  # @@protoc_insertion_point(class_scope:MessageB)
  })
_sym_db.RegisterMessage(MessageB)


# @@protoc_insertion_point(module_scope)
